### ISSUE TITLE
Git merge text

### ISSUE THREAD

**Issue by dgasmith** [MolSSI-SSS/QM_2017_SSS_Team3#44]
Looks like you missed all of the git merge text in a few [places](https://github.com/MolSSI-SSS/QM_2017_SSS_Team6/blob/master/tmp.py#L1).

**Comment by gevahn** [comment]
The link leads to a different team?

**Comment by shannonhouck** [comment]
Yup, I see it! I'll go ahead and fix it. Thanks!

**Comment by shannonhouck** [comment]
So I've found and resolved the issue in scf/init.py, but I couldn't seem to find any other instances. Let me know if you all see anything I've missed.

**Comment by dgasmith** [comment]
Aha! That was it. Apologies, looks like I copied in the wrong line.

**Comment by shannonhouck** [comment]
Ok, perfect. Thanks for letting us know!
